### ISSUE TITLE
singleInitialState

### ISSUE THREAD

**Issue by luisamaralh** [UnB-CIC/sle-course#7]
An FSM must have exactly one initial state.

**Comment by FHandrick** [comment]
Acredito que tenha terminado essa implementação.

**Comment by FHandrick** [comment]
int startElement(startState(_)) = 1;
int startElement(state(_)) = 0;
public int quantityStartState (list[State] ls) = isEmpty(ls) ? 0 : startElement(head(ls))+quantityStartState(tail(ls));

**Comment by FHandrick** [comment]
Se a quantidade de 'quantityStartState' for maior que 1, a FSM tem mais do que uma estado Inicial

**Comment by rbonifacio** [comment]
Hi Handrick, would it be possible to use comprehension on the startState(s) of an FSM and then check the resulting number of elements?

**Comment by FHandrick** [comment]
I will try refactor, using comprehension.
